### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by piolet** [octopush/Octopush-SMS-API-PHP#16]
Pouvez-vous versionner l'api à la 2.0.1 pour la gestion du simulation mode, pour éviter les problèmes de cache ?

Car actuellement, si je récupère l'api via composer, je récupère toujours une version sans simulation mode, malgré un `composer clearcache`

Merci d'avance

**Comment by octopush** [comment]
Bonjour, 

Je viens de créer une nouvelle release, v2.0.1

Pourriez vous essayer d'utiliser celle ci s'il vous plait ?

**Comment by piolet** [comment]
Merci c'est ok pour moi, j'arrive bien à récupérer la version avec le simulation mode.
