### ISSUE TITLE
(2.0.1) Code compliance with PHP requirements - syntax error in Octopush\Request\BaseRequest

### ISSUE THREAD

**Issue by mariecharles** [octopush/Octopush-SMS-API-PHP#17]
Hi,

PHP 7.3 and earlier do not support typed properties like in
Octopush\Request\BaseRequest L.15 :

```
abstract class BaseRequest
{
        /** @var string */
        protected $uri;

        /** @var string */
        protected $method;

        protected bool $simulationMode;

    […]
}
```

But here are your requirements  : "php": ">=7.1" :
[https://github.com/octopush/sms-api-php/blob/master/composer.json#L12](https://github.com/octopush/sms-api-php/blob/master/composer.json#L12)

Result:
_ParseError: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
.../octopush/sms-api/src/Request/BaseRequest.php:15
.../octopush/sms-api/src/Request/SmsCampaign/SendSmsCampaignRequest.php:10_

Thank you in advance for your help.

**Comment by octopush** [comment]
A fix has been suggested
