### ISSUE TITLE
(2.0.2) Error from SendSmsCampaignRequest - "$simulationMode must be protected (as in class Octopush\Request\BaseRequest) or weaker"

### ISSUE THREAD

**Issue by mariecharles** [octopush/Octopush-SMS-API-PHP#19]
Hi,
Thank you for your last release. However I have an error with the private 'simulationMode' written in SendSmsCampaignRequest, conflicting with the protected one in BaseRequest. Everything works perfectly without it :

<img width="1036" alt="Capture d’écran 2021-07-16 à 16 38 51" src="https://user-images.githubusercontent.com/22907202/125966715-4e52e81a-71d2-4ea0-a2bc-46c04715abda.png">

Thank you in advance for your reply

**Comment by adrienfr** [comment]
Hi @octopush, could you please look into this?

**Comment by octopush** [comment]
Hello, SendSmsCampaignRequest extends BaseRequest. simulationMode has been removed from BaseRequest to avoid conflicts. This problem is already fixed. Could you please update your file ?

**Comment by mariecharles** [comment]
Hello, the 2.0.2 does not include these changes, could you please release another version? Thank you

**Comment by piolet** [comment]
hi,

it's fix with new 2.0.3

**Comment by mariecharles** [comment]
Thanks!
